export const storeProducts = [
  {
    id: 1,
    title: 'iPhone 12',
    img: 'img/product-1.png',
    price: 899,
    companyLogo: 'apple-logo.png',
    companyName: 'Apple',
    info: `iPhone 12 in a brand new purple color. 5G to download movies on the fly and stream high-quality video. Beautifully bright 6.1-inch Super Retina XDR display. Ceramic Shield with 4x better drop performance. Incredible low-light photography with Night mode on all cameras. Cinema-grade Dolby Vision video recording, editing, and playback. Powerful A14 Bionic chip. And new MagSafe accessories for easy attach and faster wireless charging. Let the fun begin.`,
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 2,
    title: 'Samsung S21',
    img: 'img/product-2.png',
    price: 799,
    companyLogo: 'samsung-logo.png',
    companyName: 'Samsung',
    info: `The Samsung Galaxy S21 5G has a 6.2-inch display, a 64 MP rear camera, hyperfast processor, and a battery that's there when you need it most. Get creative, do things your way, and stay connected with AT&T 5G. Fast. Reliable. Secure.`,
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 3,
    title: 'iPhone 12 Pro Max',
    img: 'img/product-3.png',
    price: 1249,
    companyLogo: 'apple-logo.png',
    companyName: 'Apple',
    info: `iPhone 12 Pro Max in a brand new Pacific Blue color. 5G to download huge files on the go and stream HDR video. Larger 6.7-inch Super Retina XDR display. Ceramic Shield with 4x better drop performance. Incredible low-light photography with the best Pro camera system on an iPhone, and 5x optical zoom range. Cinema-grade Dolby Vision video recording, editing, and playback. Night mode portraits and next-level AR experiences with the LiDAR Scanner. Powerful A14 Bionic chip.`,
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 4,
    title: 'Galaxy Z Fold2',
    img: 'img/product-4.png',
    price: 1779,
    companyLogo: 'samsung-logo.png',
    companyName: 'Samsung',
    info: `The Samsung Galaxy Z Fold2 5G is a revolutionary mobile experience. With a portable design and flexible viewing options it brings the benefits of a tablet to the portability of a phone.`,
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 5,
    title: 'Galaxy Note20 Ultra',
    img: 'img/product-5.png',
    price: 1149,
    companyLogo: 'samsung-logo.png',
    companyName: 'Samsung',
    info: `The Samsung Galaxy Note20 Ultra 5G is a powerful phone as beautiful as it is intelligent with a mighty pen, a battery that keeps you going, and is as well-connected as you. The refined S Pen is more powerful than ever. It’s so responsive, it feels like you're using a real pen to jot notes and sketch ideas. Convert those ideas into a Microsoft Word document or PowerPoint with the more intelligent Samsung Notes. You can also save your notes and sync them across your Galaxy phone and tablet to give you the power to be out of office.`,
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 6,
    title: 'iPhone XR',
    img: 'img/product-6.png',
    price: 599,
    companyLogo: 'apple-logo.png',
    companyName: 'Apple',
    info: `iPhone XR features a 6.1-inch Liquid Retina display.1 Six stunning colors. Advanced Face ID lets you securely unlock your iPhone and log in to apps with just a glance. The A12 Bionic chip uses real-time machine learning to transform the way you experience photos, gaming, augmented reality (AR), and more. A 12MP camera system with Portrait mode, Portrait Lighting, enhanced bokeh, and Depth Control for studio-quality portraits. And a water-resistant design.`,
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 7,
    title: 'Apple Watch 6 LTE',
    img: 'img/product-7.png',
    price: 559,
    companyLogo: 'apple-logo.png',
    companyName: 'Apple',
    info: `Take an ECG anytime, anywhere. See your fitness metrics at a glance with the enhanced Always-On Retina display. With Apple Watch Series 6 on your wrist, a healthier, more active, more connected life is within reach.`,
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 8,
    title: 'Samsung Watch3 LTE',
    img: 'img/product-8.png',
    price: 449,
    companyLogo: 'samsung-logo.png',
    companyName: 'Samsung',
    info: `The Galaxy Watch3 combines powerful technology with a premium, customizable design so you can manage the day-to-day from your wrist. Connect to your favorite apps from your wrist via Bluetooth. Keep an eye on wellness with advanced health monitoring1.`,
    inCart: false,
    count: 0,
    total: 0,
  },
];

export const detailProduct = {
  id: 1,
  title: 'iPhone 12',
  img: 'img/product-1.png',
  price: 899,
  companyLogo: 'apple-logo.png',
  companyName: 'Apple',
  info:
    'iPhone 12 in a brand new violet color. 5G to download movies on the fly and stream high-quality video. Beautifully bright 6.1-inch Super Retina XDR display. Ceramic Shield with 4x better drop performance. Incredible low-light photography with Night mode on all cameras. Cinema-grade Dolby Vision video recording, editing, and playback. Powerful A14 Bionic chip. And new MagSafe accessories for easy attach and faster wireless charging. Let the fun begin.',
  inCart: false,
  count: 0,
  total: 0,
};
